-- Script was generated by Devart dbForge Studio Express for MySQL, Version 6.1.154.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/14/2014 10:44:37 PM
-- Server version: 5.6.12-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE evs;

--
-- Definition for table company
--
DROP TABLE IF EXISTS company;
CREATE TABLE company (
  company_id INT(11) NOT NULL AUTO_INCREMENT,
  company_name VARCHAR(200) DEFAULT NULL,
  company_size INT(11) DEFAULT NULL,
  company_image VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (company_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 2730
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  user_first_nm VARCHAR(50) DEFAULT NULL,
  user_last_nm VARCHAR(255) DEFAULT NULL,
  user_email VARCHAR(255) DEFAULT NULL,
  user_cpf VARCHAR(255) DEFAULT NULL,
  active INT(2) DEFAULT 0,
  user_password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table votes
--
DROP TABLE IF EXISTS votes;
CREATE TABLE votes (
  user_id INT(11) NOT NULL,
  company_id INT(11) NOT NULL,
  score INT(11) NOT NULL
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table company
--
INSERT INTO company VALUES
(1, 'Itau', 5000, 'itau.jpg'),
(2, 'Google', 10000, 'google.jpg'),
(3, 'Agile', 100, 'agile.png'),
(4, 'P&G', 5000, 'peg.jpg'),
(5, 'Ambev', 10000, 'ambev.jpg'),
(6, 'Volvo', 10000, 'volvo.jpg');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(2, 'Lucas', 'Zambianchi', 'kamiarc@gmail.com', '36878363802', 1, '698dc19d489c4e4db73e28a713eab07b');

-- 
-- Dumping data for table votes
--

-- Table evs.votes does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;